YmlApi:
    paths:
      - 
        name: demo/me/
        description: 単体のユーザー情報を返す123
        method: GET
        status_code: 200
        response_json_temp_file: me.json
        model: App\Models\mqtt
        response_json: |
          '{
            "id": \{\{$title \}\},
            "mail": "%rand_safeEmail%",
            "name" : "%rand_name%"
          }'
        auth: false
        requests: 
          - 
            name: required|max:5
            mail: required|max:20
      - 
        name: demo/mqtt
        method: GET
        status_code: 200
        response_json_temp_file: friends.json
        description: mqttを単体で取得
        model: App\Models\mqtt
        response_json: 
          '{
            "id": "%id%",
            "mail": "%rand_safeEmail%",
            "name" : "%rand_name%"
          }'
        requests:
          - 
            id: required
      -
        name: demo/friends
        description: 単体のユーザー情報を返す
        method: GET
        status_code: 200
        response_json_temp_file: friends.json
        model: App\Models\mqtt
        response_json: '{
            "id": %id%,
            "mail": "%rand_safeEmail%",
            "name" : "%rand_name%"
          }'
        requests: 
          -
           id: required
